//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAccountServerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcode_table
    {
        public int id { get; set; }
        public string barcode { get; set; }
        public string stockin_billno { get; set; }
        public string stockin_billtype { get; set; }
        public string product_code { get; set; }
        public string serial_no { get; set; }
        public decimal purchase_rate { get; set; }
        public decimal mrp { get; set; }
    }
}
